---
services:
  src1: &src
    image: "redis:${SRC_REDIS_VERSION:-3}"
    command: >
      redis-server
      --maxmemory            64mb
      --maxmemory-policy     allkeys-lru
      --appendonly           yes
      --cluster-enabled      yes
      --cluster-config-file  nodes.conf
      --cluster-node-timeout 5000
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "7s"
      timeout: "5s"
      retries: 10
    ports:
      - "16371:6379"
  src2:
    <<: *src
    ports:
      - "16372:6379"
  src3:
    <<: *src
    ports:
      - "16373:6379"
  src4:
    <<: *src
    ports:
      - "16374:6379"
  src5:
    <<: *src
    ports:
      - "16375:6379"
  src6:
    <<: *src
    ports:
      - "16376:6379"
  dest1: &dest
    image: "redis:${DEST_REDIS_VERSION:-5}"
    command: >
      redis-server
      --maxmemory            64mb
      --maxmemory-policy     allkeys-lru
      --appendonly           yes
      --cluster-enabled      yes
      --cluster-config-file  nodes.conf
      --cluster-node-timeout 5000
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "7s"
      timeout: "5s"
      retries: 10
    ports:
      - "16381:6379"
  dest2:
    <<: *dest
    ports:
      - "16382:6379"
  dest3:
    <<: *dest
    ports:
      - "16383:6379"
  dest4:
    <<: *dest
    ports:
      - "16384:6379"
  dest5:
    <<: *dest
    ports:
      - "16385:6379"
  dest6:
    <<: *dest
    ports:
      - "16386:6379"
  clustering:
    image: "redis:${DEST_REDIS_VERSION:-5}"
    command: >
      bash -c "apt-get update > /dev/null
      && apt-get install --no-install-recommends --no-install-suggests -y dnsutils > /dev/null
      && rm -rf /var/lib/apt/lists/*
      && yes yes | redis-cli --cluster create
      $$(dig src1 +short):6379
      $$(dig src2 +short):6379
      $$(dig src3 +short):6379
      $$(dig src4 +short):6379
      $$(dig src5 +short):6379
      $$(dig src6 +short):6379
      --cluster-replicas 1
      && yes yes | redis-cli --cluster create
      $$(dig dest1 +short):6379
      $$(dig dest2 +short):6379
      $$(dig dest3 +short):6379
      $$(dig dest4 +short):6379
      $$(dig dest5 +short):6379
      $$(dig dest6 +short):6379
      --cluster-replicas 1"
    depends_on:
      src1:
        condition: service_healthy
      src2:
        condition: service_healthy
      src3:
        condition: service_healthy
      src4:
        condition: service_healthy
      src5:
        condition: service_healthy
      src6:
        condition: service_healthy
      dest1:
        condition: service_healthy
      dest2:
        condition: service_healthy
      dest3:
        condition: service_healthy
      dest4:
        condition: service_healthy
      dest5:
        condition: service_healthy
      dest6:
        condition: service_healthy
